### ISSUE TITLE
嵌入Youtube功能

### ISSUE THREAD

**Issue by osk2** [Eric-hys/Guitar#1]
建議加入Youtube連結，方便使用者邊聽邊練

我只是搬運工，有問題找他 ↙
/cc: @hank418

**Comment by osk2** [comment]
ref: https://developers.google.com/youtube/v3/code_samples/javascript#search_by_keyword

**Comment by osk2** [comment]
resolved in 6b455fa

ref: https://developers.google.com/youtube/iframe_api_reference

**Comment by hank418** [comment]
播影片時再按別的影片沒辦法播
還有就是播影片在切到別的分類 影片還在
這..正常嗎

**Comment by hank418** [comment]
未知演唱者的時候
![2015-10-08 4 32 01](https://cloud.githubusercontent.com/assets/2628006/10361448/bfb5ec46-6dda-11e5-8551-7b3ad9ad234d.png)
![2015-10-08 4 30 05](https://cloud.githubusercontent.com/assets/2628006/10361453/ce049efa-6dda-11e5-969f-5d190ea20808.png)

**Comment by osk2** [comment]
未知演唱者搜尋失敗率高了一點，剩下都搞定了

**Comment by hank418** [comment]
壞掉了拉 
![2015-10-27 2 56 49](https://cloud.githubusercontent.com/assets/2628006/10751420/1b82994a-7cbb-11e5-876f-e948ca2c564c.png)

**Comment by hank418** [comment]
阿又好了 剛剛是youtube掛了

**Comment by osk2** [comment]
我就想說什麼都沒改怎麼會壞掉XD
