### ISSUE TITLE
吉他譜排序

### ISSUE THREAD

**Issue by hank418** [Eric-hys/Guitar#2]
排序怪怪的 好像不是照時間

**Comment by hank418** [comment]
![2015-10-07 10 09 51](https://cloud.githubusercontent.com/assets/2628006/10339911/40eaa7ac-6d40-11e5-9d57-ba610d52f67c.png)
![img_4820](https://cloud.githubusercontent.com/assets/2628006/10339935/5d72a122-6d40-11e5-9e30-5954b1d7987a.jpg)

**Comment by osk2** [comment]
看起來應該是沒用時間排序，不知道預設是以什麼排序，看來要手動排了

ref: http://stackoverflow.com/a/1069840/1348494

/cc: @Eric-hys

**Comment by hank418** [comment]
還是我的時間格式你不支援？

**Comment by hank418** [comment]
抓到了 用_id排序齁！？

**Comment by osk2** [comment]
預設應該會用第一個key排序，key的名稱好像也會排序，所以蠻有可能是_id的

**Comment by osk2** [comment]
resolved in 65723bb by appling sorting function from https://gist.github.com/umidjons/9614157
